# Generated by Django 4.1.7 on 2023-02-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletags_alter_article_author_alter_article_pic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTags',
            new_name='ArticleTag',
        ),
    ]
