# Generated by Django 4.1.7 on 2023-02-26 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_rename_articletags_articletag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('articles', models.PositiveIntegerField(default=0)),
                ('last_article_on', models.DateTimeField(blank=True, null=True)),
                ('last_thread_title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_thread_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('last_poster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_poster_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('last_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.article')),
                ('last_poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='articles.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
