# Generated by Django 4.1.7 on 2023-03-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='caption',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
