# Generated by Django 4.1.7 on 2023-03-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_remove_article_author_remove_article_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletranslation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articletranslation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='articletranslation',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='articletranslation',
            name='public',
        ),
        migrations.RemoveField(
            model_name='articletranslation',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='articletranslation',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='articles.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, to='articles.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='pic',
            field=models.URLField(max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
