# Generated by Django 4.1.7 on 2023-03-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_articletranslation_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
