# Generated by Django 4.1.7 on 2023-03-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='articles.category'),
        ),
    ]
