# Generated by Django 4.1.7 on 2023-03-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
    ]
