# Generated by Django 4.1.7 on 2023-03-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        )
    ]
