# Generated by Django 4.1.7 on 2023-03-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20230306_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='category',
            field=models.ForeignKey(default=None, help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, related_name='tag_category', to='articles.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
