# Generated by Django 4.1.7 on 2023-03-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20230306_1130'),
    ]

    operations = [
    ]
