# Generated by Django 4.1.7 on 2023-03-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_articletag_category_articletag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='articletag',
            fields=[
                ('tag', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='articletag',
            name='category',
            field=models.ForeignKey(default='', help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, related_name='tag_category', to='articles.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
