# Generated by Django 4.1.7 on 2023-03-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_articletag_category_articletag_slug'),
    ]

    operations = [

    ]
