# Generated by Django 4.1.7 on 2023-03-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_articletag_category_articletag_slug'),
    ]

    operations = [
        migrations.DeleteModel(name='articletag'),
        migrations.CreateModel(
            name='articletag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('category', models.ForeignKey(default='', help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, related_name='tag_category', to='articles.category')),
                ('slug', models.SlugField(default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.articletag'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='category',
            field=models.ForeignKey(help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, related_name='tag_category', to='articles.category'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
