# Generated by Django 4.1.7 on 2023-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_article_tags_articletag_id_alter_articletag_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
