# Generated by Django 4.1.7 on 2023-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_articletag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
