# Generated by Django 4.1.7 on 2023-03-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_picture_picture'),
        ('articles', '0020_alter_articletag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_picture', to='upload.picture'),
        ),
    ]
