###########################
# Cluster IP Service
###########################
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis-pod
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: 10.245.125.43