version: '3.8'

services:
  web:
    build: ./honkon
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh"
    volumes:
      - ./honkon/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./honkon/.env