kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-nginx-ingress
  namespace: default
data:
  proxy-connect-timeout: "10s"
  proxy-read-timeout: "10s"
  proxy-body-size: "10M"
  client-max-body-size: "10M"
  external-status-address: "10.164.15.220"