###########################
# Cluster IP Service
###########################
apiVersion: v1
kind: Service
metadata:
  name: react-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: honkon-react-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000