# Generated by Django 4.1.7 on 2023-03-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_picturesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures', verbose_name='Picture')),
                ('name', models.CharField(max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_source', to='upload.picturesource')),
                ('tags', models.ManyToManyField(blank=True, to='upload.picturetag')),
            ],
        ),
    ]
