# Generated by Django 4.1.7 on 2023-03-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_remove_article_picture'),
        ('upload', '0004_alter_picture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_picture', to='articles.article'),
        ),
    ]
