apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-cors: "true"

spec:
  rules:
  - host: inexperienceds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-cluster-ip-service
            port:
              number: 800
  - host: django.inexperienceds.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: django-cluster-ip-service
            port:
              number: 810
  - host: honkon.life
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-cluster-ip-service
            port:
              number: 80
  - host: django.honkon.life
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: django-cluster-ip-service
            port:
              number: 81