name: Backend - Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    env:
      CLUSTER_NAME: ${{ secrets.DOCN_CLUSTER_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCN_ACCESS_TOKEN }}
      - name: Login to DO Container Registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200
      - name: Start Garbage Collection
        run: doctl registry garbage-collection