name: Frontend - Build Docker Container & Push to DO Registry 

on:
  workflow_call:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-build.yaml'

jobs:
  # test_react:
  #   uses: jacksonwun/sidequestweb/.github/workflows/test-react.yaml@main
  #   secrets:
  #     REACT_APP_PROXY_HOST: ${{ secrets.REACT_APP_PROXY_HOST }}
  #     REACT_APP_BACKEND_PROXY_HOST: ${{ secrets.REACT_APP_BACKEND_PROXY_HOST }}
  #     REACT_APP_FIREBASE_APIKEY: ${{ secrets.REACT_APP_FIREBASE_APIKEY }}
  #     REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
  #     REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
  #     REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
  #     REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
  #     REACT_APP_FIREBASE_APPID: ${{ secrets.REACT_APP_FIREBASE_APPID }}
  #     REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
  build:
    runs-on: ubuntu-latest
    environment: prod
    # needs: [test_react]
    env:
      CLUSTER_NAME: ${{ secrets.DOCN_CLUSTER_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCN_ACCESS_TOKEN }}
      - name: Login to DO Container Registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200
      - name: Build Container Image
        working-directory: ./frontend/honkon
        run: |
          docker build -f Dockerfile --target builder \
            --build-arg REACT_APP_PROXY_HOST=${{ secrets.REACT_APP_PROXY_HOST }} \
            --build-arg REACT_APP_BACKEND_PROXY_HOST=${{ secrets.REACT_APP_BACKEND_PROXY_HOST }} \
            -t ${{ vars.DOCN_REGISTRY_FRONTEND }}:latest \
            -t ${{ vars.DOCN_REGISTRY_FRONTEND }}:${GITHUB_SHA::7} \
            .
        env:
          REACT_APP_PROXY_HOST: ${{ secrets.REACT_APP_PROXY_HOST }}
          REACT_APP_BACKEND_PROXY_HOST: ${{ secrets.REACT_APP_BACKEND_PROXY_HOST }}
      - name: Push Image
        run: |
          docker push ${{ vars.DOCN_REGISTRY_FRONTEND }} --all-tags
      - name: K8s cluster kubeconfig file with short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update Deployment Secrets 
        run: |
          cat << EOF >> .env.prod
          REACT_APP_PROXY_HOST=${{ secrets.REACT_PROXY_HOST }}
          REACT_APP_BACKEND_PROXY_HOST=${{ secrets.REACT_BACKEND_PROXY_HOST }}
          EOF
          kubectl delete secret ${{ secrets.DOCN_FRONTEND_SECRET_NAME }}
          kubectl create secret generic ${{ secrets.DOCN_FRONTEND_SECRET_NAME }} --from-env-file=.env.prod
      - name: Update Deployment image
        run: |
          kubectl set image deployment/${{ vars.DOCN_FRONTEND_DEPLOYMENT }} react-container=${{ vars.DOCN_REGISTRY_FRONTEND }}:${GITHUB_SHA::7}
      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/${{ vars.DOCN_FRONTEND_DEPLOYMENT }}